apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v1snim3ti-java-quarkus
  janus-idp.io/tekton: v1snim3ti-java-quarkus
  backstage.io/kubernetes-id: v1snim3ti-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: v1snim3ti-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
